spring.application.name=texnoera-crm
spring.datasource.url=jdbc:postgresql://localhost:5432/texnoera_crm
spring.datasource.username=postgres
spring.datasource.password=123
server.port=8080
server.address=0.0.0.0

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.jpa.hibernate.ddl-auto=update

